Public class AccountTriggerHandler
{
/********************************************************
Method: TranferLeadUserName
Description: Check of Transfer Leads check box field will Update Transfer Account User Name (Sales requirement for Reporting)
Author: Swathi Karkala.
Date : 11/22/2013
*********************************************************/
   /* public static void TranferAccountUserName(List<Account> newOrderList, Map<ID,Account> NewOrderMap, Map<ID,Account> oldOrderMap)
    { 
       for(Account acc:newOrderList)
       {
            if(acc.Transfer_Account__c == True)
            acc.Transfer_Account_User_Name__c = UserInfo.getLastName()+','+ UserInfo.getFirstName();       
       }
    
    } */
}